pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Automatic merge if author is kamontat
    conditions:
      - author=kamontat
    actions:
      merge:
        method: merge
